# Generated by Django 4.1.2 on 2023-06-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stats', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('workExp', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameDate', models.DateField()),
                ('gamePlace', models.CharField(max_length=20)),
                ('enemyTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.enemyteam')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchResult', models.CharField(max_length=3)),
                ('matchStats', models.CharField(max_length=50)),
                ('enemyTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.enemyteam')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.team')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.timetable')),
            ],
        ),
    ]
