# Generated by Django 4.1.2 on 2023-06-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='field_name',
            field=models.ImageField(default='', upload_to='static/media'),
        ),
    ]
