# Generated by Django 4.1.2 on 2023-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_player_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='field_name',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(default='', upload_to='static/media'),
        ),
    ]
